### ISSUE TITLE
HushChat v0

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#113]
This is a meta-issue to track issues for HushChat v0. Details for each item should go in their own Issue if needed

  - [x] Only wait for 1 conf not 3
  - [x] Use 8 zouts by default not 12
  - [x] on disk encryption of all HushChat metadata as well as existing SDL data (Duke)
  - [x] GUI tweaks related to encrypted wallet/passphrase

**Comment by leto** [comment]
@DenioD actually did the encryption, and we are very close to making v0 binaries for alpha testing

**Comment by DenioD** [comment]
this is all done :-)

**Comment by leto** [comment]
@DenioD epic work!
