### ISSUE TITLE
Lock tooltip

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#116]
```
heguli97:

it would be good if you hover your mouse over the lock that it would explain the color and state
```

Yes, we need a tooltip to explain this

**Comment by DenioD** [comment]
done https://github.com/DenioD/SilentDragonLite-1/commit/385f864d9d6990d0a9fac01b720aef0d22a04439#diff-05f1eae64901c1a85489daf03b68996fR1509 :-)
