### ISSUE TITLE
Pasting more than 512 chars gives a shitty error

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#118]
verified by sharpee

**Comment by csharpee** [comment]
A screenshot for reference of what the bug looks like.

![Screenshot from 2020-05-25 18-44-30](https://user-images.githubusercontent.com/18726788/82851371-998f2180-9ecd-11ea-9261-4e75dfccfa4c.png)

**Comment by DenioD** [comment]
done https://github.com/DenioD/SilentDragonLite-1/commit/eb0bb65230540b2a89437ae01f5a76aae537b8bc

**Comment by leto** [comment]
:tada:
