### ISSUE TITLE
I cannot only add a contact

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#120]
SDL 1.3 on Windows 10

I cannot save only a contact without send a request,
When I click on 'Only add this contact' button, I have a message saying that the address or the label cannot be empty.
Which is not the case since everything is completed. 

![20200526_2](https://user-images.githubusercontent.com/39105646/82851965-c52bff00-9f01-11ea-9027-a1c67ddb33fe.jpg)

**Comment by DenioD** [comment]
I delete the function on this place. If you add a contact here, you want to chat with him. If you only want to add a contact, without a chat verification process, you can still use the addressbook

**Comment by DenioD** [comment]
this issue can be closed too :-)
