### ISSUE TITLE
Screen not refresh after send message

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#121]
SDL v1.3 Chat on Windows 10

When I send a message, The message does not appear. If I send another one, it doesn't appear either. You have to click on another contact then return to the first one to see them appear.

Before click on another contact :
![20200526_3](https://user-images.githubusercontent.com/39105646/82852140-54d1ad80-9f02-11ea-86f6-dc7a0176c51c.jpg)

After click on another contact and return :
![20200526_4](https://user-images.githubusercontent.com/39105646/82852351-0bce2900-9f03-11ea-8367-d3f2a31429d0.jpg)

**Comment by DenioD** [comment]
done https://github.com/DenioD/SilentDragonLite-1/commit/963857fbdaa910342aff67e4a55eeaf05598101d
