### ISSUE TITLE
Draft memo is not saved if switching chats/tabs

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#125]
We should try to save any unsent writing in the memo field even if the user clicks to other chats/tabs/etc

**Comment by DenioD** [comment]
fixed https://github.com/DenioD/SilentDragonLite-1/commit/56cc89a918b22bf217eadeb1e10a209b9b4e3980#diff-585cfecf0ce15ac75be3038e77e65611R1361
