### ISSUE TITLE
Click on "Deposit Hush" button for first time crashes the app.

### ISSUE THREAD

**Issue by ab-obo** [MyHush/SilentDragonLite#140]
**Describe the bug**
Click on "Deposit Hush" button for the first time crashes the app. Using new wallet. Next time the button works normally, shows "Deposit Hush" window.

**To Reproduce**
1. Click "Deposit Hush" on "Balance" tab
2. SDL causes fatal error and stops working.

On next run the button "Deposit Hush" works as it should.

**Expected behavior**
"Deposit Hush" window appears.

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Version 1.3.4

**Additional context**

**Comment by DenioD** [comment]
fixed. Ty for reporting @ab-obo
