### ISSUE TITLE
Memo symbol counter on "Send Contact Request" window doesn't work 

### ISSUE THREAD

**Issue by ab-obo** [MyHush/SilentDragonLite#141]
![image](https://user-images.githubusercontent.com/9332836/84514360-6f55a600-acba-11ea-94a2-1bb3a7c2f0f4.png)

**Describe the bug**
Memo symbol counter doesn't change on typing a memo. 

**To Reproduce**
1. Go to "Hush Chat" tab
2. Click on "Add a new contact" button
3. Type a memo to the "Insert a memo for your request" field
4. See the counter stays on "0/512"

**Expected behavior**
The counter keeps the track of inputed symbols.

**Desktop (please complete the following information):**
 - OS: Win 7 x64
 - Version 1.3.4

**Comment by leto** [comment]
@ab-obo this works for me on Linux so this might be OS-specific

**Comment by DenioD** [comment]
fixed, ty for the report  @ab-obo
