### ISSUE TITLE
Send your friend Hush

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#153]
from https://github.com/DenioD/SilentDragonLite-1/issues/105

**Comment by leto** [comment]
@DenioD I would like to bump this up in priority. Can we add an icon somewhere near ChatItem inputs, which when clicked, would open up a small modal that allows you to input an amount of HUSH to send your contact?

**Comment by DenioD** [comment]
done

**Comment by leto** [comment]
epic!
