### ISSUE TITLE
Please add a png icon to the AppImage

### ISSUE THREAD

**Issue by probonopd** [MyHush/SilentDragonLite#161]
**Describe the bug**
Hi, thanks for making an AppImage.

Could you please add a 256x256 __png__ to `usr/share/icons/hicolor/256x256/apps/SilentDragonLite.png`?

This is needed to allow the app to pass verification and to be included in AppImageHub.
Thanks for your consideration.

**To Reproduce**
AppImage verification fails:

```
++file /tmp/.mount_BeingTbvoZno/usr/share/icons/hicolor/256x256/apps/SilentDragonLite.xpm
+ICONSIZE=
+'[' -z '' ']'
+echo 'Could not determine the size of the icon'
Could not determine the size of the icon
```

**Expected behavior**

A 256x256 __png__ is in `usr/share/icons/hicolor/256x256/apps/SilentDragonLite.png` inside the AppImage

**Additional context**
https://github.com/AppImage/appimage.github.io/pull/2055

**Comment by DenioD** [comment]
Thank you for the hint @probonopd ! I will fix that in the next release

**Comment by leto** [comment]
@probonopd thanks for reporting this! It's our first AppImage, so we didn't know about that

**Comment by leto** [comment]
@probonopd we are not giving this release out to users and will likely have another soon, but can you verify for us that the png icon looks correct? https://github.com/MyHush/SilentDragonLite/releases/tag/v1.3.5

Thanks!

**Comment by leto** [comment]
https://github.com/MyHush/SilentDragonLite/releases/tag/v1.3.6 is our latest

**Comment by jahway603** [comment]
I can confirm that a 256x256 png is inside the v1.3.9 AppImage in the location "usr/share/icons/hicolor/256x256/apps/SilentDragonLite.png". @DenioD @leto This should be closed.

**Comment by DenioD** [comment]
thanks for confirming @jahway603 :+1:  I will close this issue
