### ISSUE TITLE
ToS Next button is disabled

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#169]
SDL 1.3.6

**Describe the bug**
Next button is disabled even tho it should not be.
![tos-bug](https://user-images.githubusercontent.com/30298/85218744-26ad8500-b36b-11ea-9066-4bc3432e0fd8.png)

**To Reproduce**
1. Click "i accept"
2. Enter passphrase
3. Enter matching passphrase
4. Next button is still not active

**Expected behavior**
Next button active

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

**Additional context**
Workaround: Togging the "i accept" button a few times eventually makes the "Next" button appear.

**Comment by DenioD** [comment]
fixed
