### ISSUE TITLE
Texts cannot be translated

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#176]
SDL v1.3.8 on Windows 10

Texts cannot be translated in SDL.
- The 'Terms of service' section
- The text 'Your new HushChat address was copied to your clipboard!'
- The text 'Send Message'

There may be others.

![20200706 HUSH Send Message impossible à traduire](https://user-images.githubusercontent.com/39105646/86746619-7793cd80-c03b-11ea-8a19-082233ba96c9.PNG)
![2020-06-18_22-15-23](https://user-images.githubusercontent.com/39105646/86746624-782c6400-c03b-11ea-9f21-1f3765ce5b82.png)
![20200706 HUSH 1](https://user-images.githubusercontent.com/39105646/86746626-78c4fa80-c03b-11ea-8e9a-15a56ef5a791.PNG)

**Comment by DenioD** [comment]
https://github.com/MyHush/SilentDragonLite/commit/40721375ff8452a09ef80289eb58dd461d6ea55d should fix this issue. :+1:
