### ISSUE TITLE
Temporary name resolution should retry

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#177]
I had a very short power outage "brown out" that cycled the power + internet of my SDL connection for about 1 second. It got a "temporary name resolution" error and then got stuck, unable to refresh. Even if you right click on the status bar and hit Refresh, it's stuck with no connection.

**Comment by DenioD** [comment]
this bug should be fixed by https://github.com/MyHush/SilentDragonLite/commit/aee96977502f4ba34eff14302e7e49d87715d909 I will let this issue open till we have more testing with this fix

**Comment by DenioD** [comment]
tested and is working. I will close this Issue
