### ISSUE TITLE
Hush chats disappear

### ISSUE THREAD

**Issue by jetstream0** [MyHush/SilentDragonLite#197]
Pretty sure I am on Version 1.3.10 (latest version) on windows 10 

My hush chats disappear after closing hush chat and starting back on (typed in passphrase, ofc). I also did switch hush chat addresses using the button on hush chat accidentally, though seems like shouldn't matter

**To Reproduce**
1. Add contact and chat
(???? unknown if matters) 2. click button to change hush chat address
3. Exit and x out sdl
4. Reopen sdl, contact is gone

**Expected behavior**
Obviously, make them not disappear

**Comment by DenioD** [comment]
Thanks for reporting @jetstream0 This issue should be fixed in the next release
