### ISSUE TITLE
version 1.3.10 AppImage missing "libjbig.so.0"

### ISSUE THREAD

**Issue by jahway603** [MyHush/SilentDragonLite#198]
**Describe the bug**
The version 1.3.10 SDL AppImage does not start due to a missing shared library.

**To Reproduce**
1. Download Linux-binaries-SilentDragonLite-v1.3.10.AppImage and chmod u+x.
2. Go to command prompt & run ./Linux-binaries-SilentDragonLite-v1.3.10.AppImage.
3. Receive following error:
./Linux-binaries-SilentDragonLite-v1.3.10.AppImage: error while loading shared libraries: libjbig.so.0: cannot open shared object file: No such file or directory

**Expected behavior**
The AppImage should run correctly.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling

**Additional context**
Having trouble trying to find this share library at all with Internet searchs.

**Comment by jahway603** [comment]
@DenioD Is this shared library only available on Debian/Ubuntu? I can only find it available from the Debian/Ubuntu package called "libjbig0". Arch does not have any packages to install this shared library.

**Comment by leto** [comment]
also, what required this new dependency?

**Comment by jahway603** [comment]
This error no longer occurs in the latest Version 1.3.11 SDL AppImage. Closing this issue.
