### ISSUE TITLE
SDL Core Dump - Linux (Ubuntu) 32-bit

### ISSUE THREAD

**Issue by ghost** [MyHush/SilentDragonLite#31]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
Segmentation fault (core dumped)

**Comment by JW9898** [comment]
I tried to connect to SDL, with SDA, using the wormhole.
It wouldnt connect, so i disconnected both devices, and then the wallet core wallet dumped.

**Comment by JW9898** [comment]
"Couldn't connect. Peer is not connected." 
That is the error message I get, when trying to connect to the wormhole.

**Comment by leto** [comment]
@DenioD this happened on the latest v1.1.0

**Comment by DenioD** [comment]
Thanks alot for the issue report @JW9898 With the latest updates, we have improvements with our Wormhole, but this Coredump is not fully fix. We are working on this! Thanks again for participating

**Comment by leto** [comment]
The main reason for coredumps seems to be when our websocket times out, or is being closed and/or when retrying to open the connection. There are edge cases and/or race conditions, and sometimes code that should work, is invalid, because the `m_websocket` object is not longer fully valid for currently unknown reasons

**Comment by DenioD** [comment]
We have some improvements for our Websocket, this issue can be close
