### ISSUE TITLE
Core Dumped

### ISSUE THREAD

**Issue by ghost** [MyHush/SilentDragonLite#36]
processGetTransactions
Destroyed tempWormholeClient and ui
No network errors
Parsed JSON
Found hush key in price json
HUSH = $ "0.066464"
HUSH = € "0.060108"
HUSH = BTC "8.76e-06"
HUSH = CNY "0.467188"
HUSH = RUB "4.23"
HUSH = CAD "0.088291"
HUSH = SGD "0.09059"
HUSH = CHF "0.066006"
HUSH = INR "4.77"
HUSH = GBP "0.0515"
HUSH = AUD "0.097951"
Retrying websocket connection
Wormhole::connect
WebSocket connected
WebSocket connected, retryCount= 0
Sent registration message with code= "dd5be05a296566493ba72f0483d10c8babde80e083e58e556e85a0343c31a3c1"
Created QTimer
Started timer with interval= 240000
Timer timeout!
Segmentation fault (core dumped)

**Comment by DenioD** [comment]
Can you provide more information @JW9898 Like: What you did before the dump happend, Are sdl  connected to a phone? 

Thank you!

**Comment by leto** [comment]
Closing this, we improved this websocket code
