### ISSUE TITLE
Recurring payment json file location

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#4]
This directory location might need to change and we also need to correctly see if the log file exists before trying to log to it.

```
QIODevice::read (QFile, "/home/duke/.local/share/myhush.org/SilentDragonLite/recurringpayments.json"): device not open
```

**Comment by leto** [comment]
@DenioD was this fixed?

**Comment by DenioD** [comment]
no have to fix it. Thanks for the reminder @leto

**Comment by leto** [comment]
@DenioD recurring payments is not enabled in SD, is it possible for SDL users to do recurring payments by default?

**Comment by DenioD** [comment]
@leto In SDL its also not enabled. Its a fail error. SDL should not search for it.

**Comment by leto** [comment]
👍

**Comment by DenioD** [comment]
fixed
