### ISSUE TITLE
OpenSSL 1.0.x is no longer supported

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#73]
As per the OpenSSL website: 

Note: The latest stable version is the 1.1.1 series. This is also our Long Term Support (LTS) version, supported until 11th September 2023. All other versions (including 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used. Users of these older versions are encourage to upgrade to 1.1.1 as soon as possible. Extended support for 1.0.2 to gain access to security fixes for that version is available.

SD+SDL should see if we are compatible with 1.1.x and and upgrade

**Comment by DenioD** [comment]
we use 1.1.1 :-)
