### ISSUE TITLE
The amount sent is not exact. Decimals are missing.

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#76]
The amount sent is not exact. I think the decimals are missing.

**To Reproduce**
I have 1 Hush
I send 0.9999 with 0.0001 fee from my zAddress to the same zAddress
I see 0 Hush sent from GUI SDL

**Expected behavior**
See 1 Hush send or 0.9999 Hush not 0 Hush.

**Desktop :**
 - OS: Windows 10

**Additional context**
![20200124 Decimal SDL](https://user-images.githubusercontent.com/39105646/73106261-4a26ed80-3efb-11ea-8931-ccef1a8a63cf.jpg)

**Comment by gilardh** [comment]
![20200124 Decimal SDL 2](https://user-images.githubusercontent.com/39105646/73107234-97a45a00-3efd-11ea-876d-28c1ab02e602.jpg)

**Comment by DenioD** [comment]
SDL shows sendingings to the same zaddr as 0 amount. Tbh I don't see any benefit to change it, since the sending to the same zaddr is very unlikely.

**Comment by gilardh** [comment]
Sending to the same zaddr is very unlikely but I did it. ;o) 

Decimals are clearly visible when transferring funds to another address than one's own  :
![20200125 SDL](https://user-images.githubusercontent.com/39105646/73119726-6e6be400-3f66-11ea-9fda-a0833fec22ae.jpg)

**Comment by DenioD** [comment]
Maybe I can give a warning for this, but I can see no use case to send to the same zaddr (expect to burn fees maybe)
