### ISSUE TITLE
The font size of the words 'Privé', 'Notarizé' and 'Transparant' are not the same size.

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#77]
The font size of the words 'Privé', 'Notarizé' and 'Transparant' are not the same size.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
![20200124 Decimal SDL 2](https://user-images.githubusercontent.com/39105646/73107258-aab72a00-3efd-11ea-8016-3b682ba1a248.jpg)

**Comment by DenioD** [comment]
Thanks will look into this

**Comment by DenioD** [comment]
Fixed. Thanks for reporting!
